# Generated by Django 5.1.5 on 2025-01-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('password', 'Password'), ('textarea', 'Textarea')], max_length=50)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
    ]
