# Generated by Django 5.1.5 on 2025-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/images/social_icons/')),
                ('url', models.URLField()),
            ],
        ),
    ]
